"use server";
import { createClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";
async function auth(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();return {supabase,user};}
export async function getGoals(eventId:string){const {supabase}=await auth();const {data}=await supabase.from("goals").select("id,title,created_at").eq("event_id",eventId).order("created_at");return data??[];}
export async function createGoal(eventId:string,title:string){const {supabase,user}=await auth();if(!user)return{error:"You must be logged in."};const clean=title.trim();if(!clean||clean.length>300)return{error:"Goal is invalid."};const {error}=await supabase.from("goals").insert({event_id:eventId,title:clean});if(error)return{error:error.message};revalidatePath(`/events/${eventId}`);return{ok:true as const};}
export async function updateGoal(goalId:string,eventId:string,title:string){const {supabase,user}=await auth();if(!user)return{error:"You must be logged in."};const clean=title.trim();if(!clean||clean.length>300)return{error:"Goal is invalid."};const {error}=await supabase.from("goals").update({title:clean}).eq("id",goalId).eq("event_id",eventId);if(error)return{error:error.message};revalidatePath(`/events/${eventId}`);return{ok:true as const};}
export async function deleteGoal(goalId:string,eventId:string){const {supabase,user}=await auth();if(!user)return{error:"You must be logged in."};const {error}=await supabase.from("goals").delete().eq("id",goalId).eq("event_id",eventId);if(error)return{error:error.message};revalidatePath(`/events/${eventId}`);return{ok:true as const};}
export async function getNotes(eventId:string){const {supabase}=await auth();const {data}=await supabase.from("notes").select("id,content,updated_at,created_at").eq("event_id",eventId).order("created_at");return data??[];}
export async function saveNote(noteId:string|null,eventId:string,content:string){const {supabase,user}=await auth();if(!user)return{error:"You must be logged in."};if(content.length>10000)return{error:"Note is too long."};const r=noteId?await supabase.from("notes").update({content,updated_at:new Date().toISOString()}).eq("id",noteId).eq("event_id",eventId).select("id").single():await supabase.from("notes").insert({event_id:eventId,content}).select("id").single();if(r.error)return{error:r.error.message};revalidatePath(`/events/${eventId}`);return{ok:true as const,id:r.data.id};}
export async function deleteNote(noteId:string,eventId:string){const {supabase,user}=await auth();if(!user)return{error:"You must be logged in."};const {error}=await supabase.from("notes").delete().eq("id",noteId).eq("event_id",eventId);if(error)return{error:error.message};revalidatePath(`/events/${eventId}`);return{ok:true as const};}
export async function getSchedule(eventId:string){const {supabase}=await auth();const {data}=await supabase.from("schedule_items").select("id,title,start_at,end_at,created_at").eq("event_id",eventId).order("start_at");return data??[];}
export async function createScheduleItem(eventId:string,title:string,startAt:string,endAt?:string|null){const {supabase,user}=await auth();if(!user)return{error:"You must be logged in."};const clean=title.trim();const start=new Date(startAt);const end=endAt?new Date(endAt):null;if(!clean||Number.isNaN(start.getTime())||(end&&Number.isNaN(end.getTime()))||(end&&end<=start))return{error:"Invalid schedule item."};const {error}=await supabase.from("schedule_items").insert({event_id:eventId,title:clean,start_at:start.toISOString(),end_at:end?.toISOString()??null});if(error)return{error:error.message};revalidatePath(`/events/${eventId}`);return{ok:true as const};}
export async function updateScheduleItem(id:string,eventId:string,title:string,startAt:string,endAt?:string|null){const {supabase,user}=await auth();if(!user)return{error:"You must be logged in."};const start=new Date(startAt);const end=endAt?new Date(endAt):null;if(!title.trim()||Number.isNaN(start.getTime())||(end&&Number.isNaN(end.getTime()))||(end&&end<=start))return{error:"Invalid schedule item."};const {error}=await supabase.from("schedule_items").update({title:title.trim(),start_at:start.toISOString(),end_at:end?.toISOString()??null}).eq("id",id).eq("event_id",eventId);if(error)return{error:error.message};revalidatePath(`/events/${eventId}`);return{ok:true as const};}
export async function deleteScheduleItem(id:string,eventId:string){const {supabase,user}=await auth();if(!user)return{error:"You must be logged in."};const {error}=await supabase.from("schedule_items").delete().eq("id",id).eq("event_id",eventId);if(error)return{error:error.message};revalidatePath(`/events/${eventId}`);return{ok:true as const};}
