"use server";
import { createClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";
function validTimezone(tz:string){try{new Intl.DateTimeFormat("en-US",{timeZone:tz});return true}catch{return false}}
export async function getReminders(eventId:string){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return[];const {data}=await supabase.from("reminders").select("id,event_id,task_id,remind_at,timezone,title,sent_at,created_at").eq("event_id",eventId).order("remind_at");return data??[];}
export async function createReminder(eventId:string,input:{title:string;remindAt:string;timezone:string;taskId?:string|null}){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{error:"You must be logged in."};const title=input.title.trim();const at=new Date(input.remindAt);if(!title||title.length>200)return{error:"Reminder title is invalid."};if(!validTimezone(input.timezone))return{error:"Timezone is invalid."};if(Number.isNaN(at.getTime())||at.getTime()<=Date.now())return{error:"Reminder must be in the future."};if(input.taskId){const {data:task}=await supabase.from("tasks").select("id").eq("id",input.taskId).eq("event_id",eventId).maybeSingle();if(!task)return{error:"Task does not belong to this event."};}const {error}=await supabase.from("reminders").insert({event_id:eventId,task_id:input.taskId??null,remind_at:at.toISOString(),timezone:input.timezone,title});if(error)return{error:error.message};revalidatePath(`/events/${eventId}`);return{ok:true as const};}
export async function deleteReminder(reminderId:string,eventId:string){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{error:"You must be logged in."};const {error}=await supabase.from("reminders").delete().eq("id",reminderId).eq("event_id",eventId);if(error)return{error:error.message};revalidatePath(`/events/${eventId}`);return{ok:true as const};}
export async function savePushSubscription(subscription:{endpoint:string;keys?:{p256dh?:string;auth?:string};userAgent?:string}){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{error:"You must be logged in."};if(!subscription.endpoint||!subscription.keys?.p256dh||!subscription.keys.auth)return{error:"Invalid push subscription."};const {error}=await supabase.from("push_subscriptions").upsert({user_id:user.id,endpoint:subscription.endpoint,p256dh:subscription.keys.p256dh,auth:subscription.keys.auth,user_agent:subscription.userAgent??null,updated_at:new Date().toISOString()},{onConflict:"endpoint"});if(error)return{error:error.message};return{ok:true as const};}
export async function removePushSubscription(endpoint:string){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{error:"You must be logged in."};const {error}=await supabase.from("push_subscriptions").delete().eq("endpoint",endpoint).eq("user_id",user.id);if(error)return{error:error.message};return{ok:true as const};}
